x = {
    "manifest": {
        "kind": {
            "document": "You should define description"
        },
        "name": {
            "document": "You should define description"
        },
        "internal": {
            "spec": {
                "image": {
                    "document": "Image is name of the image that you want to create\n"
                                "your service from.\n"
                                "images can be defined in three ways:\n"
                                "1- IMAGE_NAME:IMAGE_VERSION, which refers to an image already existing in your "
                                "namespace\n "
                                "2- library/IMAGE_NAME:IMAGE_VERSION, which refers to an image existing on docker hub\n"
                                "3- REGISTRY_URL/IMAGE_NAME:IMAGE_VERSION, which refers to an image which exists on a "
                                "different private registry\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec:\n"
                                "  image: IMAGE_NAME:IMAGE_TAG\n"
                                "  ...\n"
                }, "port": {
                    "document": "port structure should be like this:\n\n"
                                "kind: InternalService\n"
                                "name: SERVICE_NAME\n"
                                "spec:\n"
                                "  ...\n"
                                "  port: integer_port_number\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n "

                }, "image_pull_policy": {
                    "document": "image_pull_policy gives you the option to always pull your image\n"
                                "for every service deploy that you make if it's value is set to \"Always\"\n"
                                "if you don't specify this field, then the default value will be \"IfNotPresent\"\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  image_pull_policy: [Always, IfNotPresent] default = IfNotPresent\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"

                }, "image_pull_secret": {
                    "document": "image_pull_secret is used for situations in which you want to\n"
                                "pull an image from a private registry; in order to achieve this\n"
                                "you have to pass the name of the secret that you have built before\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  image_pull_secret: \"private-registry-secret\"\n"
                                "  ...\n"
                                "for more info visit manifest and secret documents in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n"
                                "https://docs.fandogh.cloud/docs/secret.html\n\n"
                }, "replicas": {
                    "document": "replica indicates the number of instances that should be made\n"
                                "from your manifest and it's default value is \"1\"\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  replica: REPLICA_COUNT default = 1\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"
                }, "env": {
                    "document": "env is used for declaring environment variables\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  env:\n"
                                "   - name: KEY_ONE\n"
                                "     value: VALUE_ONE\n"
                                "   - name: KEY_TWO\n"
                                "     value: VALUE_TWO\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"

                }, "port_mapping": {
                    "document": "port_mapping gives your internal services ability to expose\n"
                                "themselves on ports other than their default ones."
                                "Note that using port_mapping you can only expose your services\n"
                                "in the namespace, not outside it!"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  port_mapping:\n"
                                "   - port: PORT_NUMBER\n"
                                "     target_port: TARGET_PORT_NUMBER\n"
                                "     protocol: [TCP, UDP] default = TCP\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"
                }, "volume_mounts": {
                    "document": "volume_mounts give you the option to persist your data just by mounting\n"
                                "your preferred data path from your service to a storage directory.\n"
                                "Note: if you don't use volume_name then all your data will be written on your\n"
                                "shared storage directory.\n"
                                "Note that if you intend to use dedicated volumes, you have to \n"
                                "create a dedicated volume and each volume can be attached only to one service.\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  volumes:\n"
                                "   - volume_name: VOLUME_NAME\n"
                                "     mount_path: MOUNT_PATH_ONE\n"
                                "     sub_path: SUB_PATH_ONE\n\n"
                                "   - mount_path: MOUNT_PATH_TWO\n"
                                "     sub_path: SUB_PATH_TWO\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"

                }, "resources": {
                    "document": "resources indicates how much resource your service will use.\n"
                                "in order to specify desired memory for your service, you have to\n"
                                "write it in Mib format like -> 1024Mi which means a service that want to use 1Gb "
                                "memory\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  resources:\n"
                                "   - memory: MEMORY_IN_MIB, default -> 200Mi"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"

                }, "liveness_probe": {
                    "document": "liveness_probe helps you check your service health each time\n"
                                "in a specific period of time that you decide.\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  liveness_probe:\n"
                                "    initial_delay_seconds: INITIAL_DELAY_IN_SECONDS\n"
                                "      period_seconds: PERIOD_INTERVAL_IN_SECONDS\n"
                                "      http_get:\n"
                                "        path: URL_TO_BE_CHECKED\n"
                                "        port: PORT_NUMBER"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"

                }, "readiness_probe": {
                    "document": "readiness_probe helps you check to see whether your service is completely booted up "
                                "or not. this way you can prevent your dependent services from failing to send "
                                "request\n"
                                "to some services that are still booting up.\n"
                                "in a specific period of time that you decide.\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  readiness_probe:\n"
                                "    initial_delay_seconds: INITIAL_DELAY_IN_SECONDS\n"
                                "      period_seconds: PERIOD_INTERVAL_IN_SECONDS\n"
                                "      http_get:\n"
                                "        path: URL_TO_BE_CHECKED\n"
                                "        port: PORT_NUMBER"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"

                }
            }
        },
        "external": {
            "spec": {
                "document": "You should define description",
                "domains": {
                    "document": "domains spec is list of domains that you want to add\n"
                                "to your service, below is the sample:\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  domains:\n"
                                "   - name: DOMAIN_NAME_ONE\n"
                                "   - name: DOMAIN_NAME_TWO\n"
                }, "allow_http": {
                    "document": "allow_http helps you to expose your service\n"
                                "on non-ssl protocol http\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name: SERVICE_NAME\n"
                                "spec:\n"
                                "  ...\n"
                                "  allow_http: [false, true, default=true]\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n "
                }, "path": {
                    "document": "\"path\" helps you to response to requests on a\n"
                                "specific path\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name: SERVICE_NAME\n"
                                "spec:\n"
                                "  ...\n"
                                "  path: PATH_FROM_ROOT\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n "
                }
            }
        },
        "managed": {
            "service_name": {
                "document": "service_name is the name of your service that you have to specify\n"
                            "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                            "name: SERVICE_NAME\n"
                            "spec:\n"
                            "  ...\n"
                            "for more info visit manifest in:\n"
                            "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"
            }, "version": {
                "document": "version indicates the version of managed-service image.\n"
                            "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                            "name: SERVICE_NAME\n"
                            "version: SERVICE_IMAGE_VERSION\n"
                            "spec:\n"
                            "  ...\n"
                            "for more info visit manifest in:\n"
                            "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"
            }, "spec": {
                "document": "document for managed services",
                "parameters": {
                    "document": "parameters are some specific fields that are related to each managed service\n"
                                "using command [fandogh managed-service help] you can see parameters related to each\n"
                                "managed-managed service.\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name: SERVICE_NAME\n"
                                "spec:\n"
                                "  ...\n"
                                "  parameters:\n"
                                "   - name: PARAM_NAME_ONE\n"
                                "     value: PARAM_VALUE_ONE\n"
                                "   - name: PARAM_NAME_TWO\n"
                                "     value: PARAM_VALUE_TWO\n"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"
                }, "resources": {
                    "document": "resources indicates how much resource your service will use.\n"
                                "in order to specify desired memory for your service, you have to\n"
                                "write it in Mib format like -> 1024Mi which means a service that want to use 1Gb "
                                "memory\n"
                                "kind: SERVICE_KIND[ExternalService, InternalService, ManagedService]\n"
                                "name:SERVICE_NAME\n"
                                "spec\n"
                                "  ...\n"
                                "  resources:\n"
                                "   - memory: MEMORY_IN_MIB, default -> 200Mi"
                                "  ...\n"
                                "for more info visit manifest in:\n"
                                "https://docs.fandogh.cloud/docs/service-manifest.html\n\n"

                }
            }
        }
    }
}
